### ISSUE TITLE
class LedMatrixSPI' has no member named 'drawChar'

### ISSUE THREAD

**Issue by RupinC** [agr00m/LedMatrixSPI#1]
ScrollingText:135: error: 'class LedMatrixSPI' has no member named 'drawChar'

          lm.drawChar(text[i], x + ((FONT5x7 + 1) * i), 8);

Got this error While compiling the Scrolling Text example.

**Comment by agr00m** [comment]
woops, looks like I changed it to printChar(), but didn't update the example. 
Updated the example if you want to download it again, or just change it to printChar.
Thanks for the heads up!
